var video_jason=[
	{
		video_cover:"img/product_06.jpg",	//封面图片
		video_url:'//static.hdslb.com/miniloader.swf?aid=14193479',	//视频/图片连接
		//video_url : '<embed height="640" width="911.5" quality="high" allowfullscreen="true" type="application/x-shockwave-flash" src="//static.hdslb.com/miniloader.swf" flashvars="aid=14193479&page=1" pluginspage="//www.adobe.com/shockwave/download/download.cgi?P1_Prod_Version=ShockwaveFlash"></embed>',
		video_name:'龙武2'	//视频/图片名称
	},
	{
		video_cover:"img/product_07.jpg",
		video_url:'//static.hdslb.com/miniloader.swf?aid=14218898',
		video_name:'天天枪战'
	},
	{
		video_cover:"img/product_08.jpg",
		video_url:'//static.hdslb.com/miniloader.swf?aid=14194864',
		video_name:'迷雾'
	},
	{
		video_cover:"img/product_09.jpg",
		video_url:'//static.hdslb.com/miniloader.swf?aid=14195620',
		video_name:'思美人'
	},
	{
		video_cover:"img/product_10.jpg",
		video_url:'//static.hdslb.com/miniloader.swf?aid=14218759',
		video_name:'天天炫斗剪辑'
	},
	{
		video_cover:"img/product_11.jpg",
		video_url:'http://static.hdslb.com/miniloader.swf?aid=14194091',
		video_name:'卢卡斯'
	},
	{
		video_cover:"img/product_12.jpg",
		video_url:'http://static.hdslb.com/miniloader.swf?aid=14195132',
		video_name:'尸兄'
	},
	{
		video_cover:"img/product_13.jpg",
		video_url:'http://static.hdslb.com/miniloader.swf?aid=14193979',
		video_name:'龙族要塞1'
	},
	{
		video_cover:"img/product_14.jpg",
		video_url:'http://static.hdslb.com/miniloader.swf?aid=14193979',
		video_name:'龙族要塞2'
	},
	{
		video_cover:"img/product_15.jpg",
		video_url:'http://static.hdslb.com/miniloader.swf?aid=14193979',
		video_name:'龙族要塞3'
	},
	{
		video_cover:"img/product_16.jpg",
		video_url:'http://static.hdslb.com/miniloader.swf?aid=14217316',
		video_name:'星际传奇'
	},
	{
		video_cover:"img/product_17.jpg",
		video_url:'http://static.hdslb.com/miniloader.swf?aid=14217158',
		video_name:'微信微粒贷'
	},
	{
		video_cover:"img/product_18.jpg",
		video_url:'http://static.hdslb.com/miniloader.swf?aid=14245279',
		video_name:'佛陀传'
	},
	{
		video_cover:"img/product_19.jpg",
		video_url:'http://static.hdslb.com/miniloader.swf?aid=14193289',
		video_name:'爆爆王国'
	},
	{
		video_cover:"img/product_20.jpg",
		video_url:'http://static.hdslb.com/miniloader.swf?aid=14192850',
		video_name:'百田'
	},
	{
		video_cover:"img/product_21.jpg",
		video_url:'http://static.hdslb.com/miniloader.swf?aid=14193090',
		video_name:'阿修罗1'
	},
	{
		video_cover:"img/product_22.jpg",
		video_url:'http://static.hdslb.com/miniloader.swf?aid=14193090',
		video_name:'阿修罗2'
	},
	{
		video_cover:"img/product_23.jpg",
		video_url:'video/思美人Tpose.jpg',
		video_name:'思美人Tpose'
	},
	{
		video_cover:"img/product_24.jpg",
		video_url:'video/龙武刀妹Tpose.png',
		video_name:'龙武刀妹Tpose'
	},
	{
		video_cover:"img/product_25.jpg",
		video_url:'video/天天枪战Tpose1.png',
		video_name:'天天枪战Tpose1'
	},
	{
		video_cover:"img/product_26.jpg",
		video_url:'video/天天枪战Tpose2.png',
		video_name:'天天枪战Tpose2'
	},
	{
		video_cover:"img/product_27.jpg",
		video_url:'video/天天枪战Tpose3.png',
		video_name:'天天枪战Tpose3'
	},
	{
		video_cover:"img/product_28.jpg",
		video_url:'',
		video_name:''
	},
	{
		video_cover:"img/product_29.jpg",
		video_url:'',
		video_name:''
	},
	{
		video_cover:"img/product_30.jpg",
		video_url:'',
		video_name:''
	}
];

var introduce_cg='CG是计算机动画（Computer Animation）的缩写。通常分为二维动画和三维动画两种。CG业务几乎囊括了当今电脑时代中所有的视觉艺术创作活动。目前我司CG业务水平位于国内CG行业前列水平。为游戏公司制作了多部优秀作品。';
var introduce_series='动画连续剧业务，多于各大动画电视台有网络播放。我司已与多家优秀动画公司合作，参与制作多部连接剧动画。均登陆央视少儿、金鹰卡通等收视率排名前列的电视台全国播放。所登陆网络平台均超过1亿点播量。';
var introduce_movie='电影业务是指院线动画电影（包括部分真人电影中的特效制作），目前我司与业内知名动画公司达成合作协议，参与制作优质大型动画电影《大闹西游》，电影将于春节档期强势登陆各大院线。';