var video_jason=[
	{
		video_cover:"img/product_06.jpg",	//封面图片
		video_url:'video/龙武2刀妹.mov',	//视频/图片连接
		video_name:'龙武2'	//视频/图片名称
	},
	{
		video_cover:"img/product_07.jpg",
		video_url:'video/天天枪战2.mp4',
		video_name:'天天枪战'
	},
	{
		video_cover:"img/product_08.jpg",
		video_url:'video/迷雾.mov',
		video_name:'迷雾'
	},
	{
		video_cover:"img/product_09.jpg",
		video_url:'video/思美人.mov',
		video_name:'思美人'
	},
	{
		video_cover:"img/product_10.jpg",
		video_url:'video/天天炫斗剪辑.mp4',
		video_name:'天天炫斗剪辑'
	},
	{
		video_cover:"img/product_11.jpg",
		video_url:'video/卢卡斯.mov',
		video_name:'卢卡斯'
	},
	{
		video_cover:"img/product_12.jpg",
		video_url:'video/尸兄.mp4',
		video_name:'尸兄'
	},
	{
		video_cover:"img/product_13.jpg",
		video_url:'video/龙族要塞1.mov',
		video_name:'龙族要塞1'
	},
	{
		video_cover:"img/product_14.jpg",
		video_url:'video/龙族要塞2.mov',
		video_name:'龙族要塞2'
	},
	{
		video_cover:"img/product_15.jpg",
		video_url:'video/龙族要塞3.mov',
		video_name:'龙族要塞3'
	},
	{
		video_cover:"img/product_16.jpg",
		video_url:'video/星际传奇.mov',
		video_name:'星际传奇'
	},
	{
		video_cover:"img/product_17.jpg",
		video_url:'video/微粒贷15秒.mp4',
		video_name:'微信微粒贷'
	},
	{
		video_cover:"img/product_18.jpg",
		video_url:'video/佛陀传_Final.mov',
		video_name:'佛陀传'
	},
	{
		video_cover:"img/product_19.jpg",
		video_url:'video/爆爆王国.mp4',
		video_name:'爆爆王国'
	},
	{
		video_cover:"img/product_20.jpg",
		video_url:'video/百田奥义联盟.mov',
		video_name:'百田'
	},
	{
		video_cover:"img/product_21.jpg",
		video_url:'video/阿修罗_1.mp4',
		video_name:'阿修罗1'
	},
	{
		video_cover:"img/product_22.jpg",
		video_url:'video/阿修罗2.mov',
		video_name:'阿修罗2'
	},
	{
		video_cover:"img/product_23.jpg",
		video_url:'video/吕布.jpg',
		video_name:'吕布渲染图'
	},
	{
		video_cover:"img/product_24.jpg",
		video_url:'video/貂蝉 变身后.jpg',
		video_name:'貂蝉变身后渲染图'
	},
	{
		video_cover:"img/product_25.jpg",
		video_url:'video/貂蝉 变身前.jpg',
		video_name:'貂蝉变身前渲染图'
	},
	{
		video_cover:"img/product_26.jpg",
		video_url:'video/貂蝉变身前3-细化22.jpg',
		video_name:'貂蝉原画'
	},
	{
		video_cover:"img/product_27.jpg",
		video_url:'video/貂蝉变身后后后1117-恢复的.jpg',
		video_name:'貂蝉原画'
	},
	{
		video_cover:"img/product_28.jpg",
		video_url:'',
		video_name:''
	},
	{
		video_cover:"img/product_29.jpg",
		video_url:'',
		video_name:''
	},
	{
		video_cover:"img/product_30.jpg",
		video_url:'',
		video_name:''
	}
];